### ISSUE TITLE
Unable to execute the code and getting errors.

### ISSUE THREAD

**Issue by rkchaitu87** [dbouchabou/Fully-Convolutional-Network-Smart-Homes#1]
Hello,
Thanks for sharing your work. I am also working on the same area. Actually I tried to run the code but getting some errors. It would be grateful if you mention the tensorflow and other packages version used by you. May be due to version changes it is not executing.

**Comment by dbouchabou** [comment]
Thank you for this return, i'll check this in the few days.
Maybe it is due to the used tensforflow version.

**Comment by rkchaitu87** [comment]
Yeah maybe. If possible provide the versions of packages used and highlight the changes if any. Waiting for your reply.

While running the main.py file, I am getting this error.
**Input command:** _python main.py --i MILAN_activity_sequences_windowed_25_padded --d datasets/pre_processed_datasets/MILAN --c batch_1024_epoch_400_early_stop_mask_0.0 --m FCN_Embedded FCN_

**Error:**
_Traceback (most recent call last):
  File "E:\Research\Research\Codes\Fully-Convolutional-Network-Smart-Homes-master\main.py", line 404, in <module>
    plot_model(model, show_shapes=True, to_file=picture_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\vis_utils.py", line 434, in plot_model
    dot.write(to_file, format=extension)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydot.py", line 1829, in write
    with io.open(path, mode='wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results\\FCN_Embedded\\run_MILAN_activity_sequences_windowed_25_padded_batch_1024_epoch_400_early_stop_mask_0.0_2022_02_08_16_12_54\\FCN_Embedded_MILAN_activity_sequences_windowed_25_padded_batch_1024_epoch_400_early_stop_mask_0.0_0.png'_

**Comment by dbouchabou** [comment]
I created a new clean git clone and followed the readme. 
Everythings worked.
I'm under Tensorflow 2.4.1 and a Linux OS.

It seems you used the code under Windows and look at the error copy it seems that you have an error of path.
The code cannot open the file "FCN_Embedded_MILAN_activity_sequences_windowed_25_padded_batch_1024_epoch_400_early_stop_mask_0.0_0.png".
Do have the rights to write files under your system ?
Could you check if the folder "results" is correctly created ?
Could you try to change the input command with "\" and not "/", I think that under windows os you must use "/" for path .

**Comment by rkchaitu87** [comment]
Yes. I am running it in windows 10 and i used tensorflow latest version. The folder is getting created but file is not there. Now,  I'll try it in Linux and check it.  Can you suggest some improvement areas so that it can be helpful for ky research work. Thanks in advance.

**Comment by rkchaitu87** [comment]
Hello, 
I was able to successfully compile your code in windows by making little changes for the path. But the time taken for training and validation is huge. Thanks for sharing your work. Good Luck.
